!macro NSIS_HOOK_POSTINSTALL
  Rename "$DESKTOP\${MAINBINARYNAME}.lnk" "$DESKTOP\Motrix Next.lnk"
  Rename "$SMPROGRAMS\${STARTMENUFOLDER}\${MAINBINARYNAME}.lnk" "$SMPROGRAMS\${STARTMENUFOLDER}\Motrix Next.lnk"
!macroend
